# Generated by Django 4.2.6 on 2024-01-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contact_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactmodel',
        ),
    ]
