# Generated by Django 4.2.6 on 2024-01-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contactmodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='subject',
            field=models.CharField(default='general inquiry', max_length=100),
        ),
    ]
